export const products = [
  {
    id: 1,
    name: 'VIVO ',
    price: '7499/-',
    branch: 'BARRACKPORE',
    age: '6 months',
    imei: '123456789012345',
    condition: 'Used',
    color: 'Black',
    storage: '6/128GB',
    availability: 'In Stock',
    image: 'https://billing.mobixpress.in/uploads/brand/itel.jpg',
    discount: 1000,
  },
  {
    id: 2,
    name: 'VIVO ',
    price: '23000/-',
    branch: 'KOLKATA',
    age: '1 year',
    imei: '987654321012345',
    condition: 'New',
    color: 'Silver',
    storage: '8/256GB',
    availability: 'Out of Stock',
    image: 'https://billing.mobixpress.in/uploads/brand/lava.jpg',
    discount: 1100,
  },
  {
    id: 3,
    name: 'REALME ',
    price: '10999/-',
    branch: 'BARRACKPORE',
    age: '8 months',
    imei: '192837465091283',
    condition: 'Used',
    color: 'Blue',
    storage: '4/64GB',
    availability: 'In Stock',
    image: 'https://billing.mobixpress.in/uploads/brand/mi.jpg',
    discount: 1000,
  },
  {
    id: 4,
    name: 'Samsung ',
    price: '29999/-',
    branch: 'KOLKATA',
    age: '1 year',
    imei: '456789012345678',
    condition: 'New',
    color: 'White',
    storage: '6/128GB',
    availability: 'In Stock',
    image: 'https://billing.mobixpress.in/uploads/brand/motorola.jpg',
    discount: 1500,
  },
  {
    id: 5,
    name: 'OnePlus',
    price: '35999/-',
    branch: 'BARRACKPORE',
    age: '5 months',
    imei: '654987123456789',
    condition: 'New',
    color: 'Green',
    storage: '6/256GB',
    availability: 'In Stock',
    image: 'https://billing.mobixpress.in/uploads/brand/poco.jpg',
    discount: 1600,
  },
  {
    id: 6,
    name: 'iPhone ',
    price: '99999/-',
    branch: 'BARRACKPORE',
    age: 'New',
    imei: '987654321654987',
    condition: 'New',
    color: 'Space Grey',
    storage: '8/128GB',
    availability: 'In Stock',
    image: 'https://billing.mobixpress.in/uploads/brand/oneplus.jpg',
    discount: 1700,
  },
  {
    id: 7,
    name: 'Xiaomi',
    price: '14999/-',
    branch: 'BARRACKPORE',
    age: '3 months',
    imei: '456123789098654',
    condition: 'Used',
    color: 'Black',
    storage: '4/64GB',
    availability: 'In Stock',
    image: 'https://billing.mobixpress.in/uploads/brand/oppo.jpg',
    discount: 1800,
  },
  {
    id: 8,
    name: 'Oppo',
    price: '23999/-',
    branch: 'KOLKATA',
    age: '2 months',
    imei: '567123456123789',
    condition: 'Used',
    color: 'Purple',
    storage: '6/128GB',
    availability: 'Out of Stock',
    image: 'https://billing.mobixpress.in/uploads/brand/realme.jpg',
    discount: 1900,
  },
  {
    id: 9,
    name: 'Realme',
    price: '41999/-',
    branch: 'BARRACKPORE',
    age: '10 months',
    imei: '111223344556677',
    condition: 'New',
    color: 'Blue',
    storage: '6/256GB',
    availability: 'In Stock',
    image: 'https://billing.mobixpress.in/uploads/brand/samsung.jpg',
    discount: 2100,
  },
  {
    id: 10,
    name: 'Poco',
    price: '17999/-',
    branch: 'KOLKATA',
    age: '6 months',
    imei: '654123789098123',
    condition: 'Used',
    color: 'Yellow',
    storage: '128GB',
    availability: 'In Stock',
    image: 'https://billing.mobixpress.in/uploads/brand/tecno.jpg',
    discount: 1000,
  },
  {
    id: 11,
    name: 'VIVO ',
    price: '22999/-',
    branch: 'DELHI',
    age: '1 year',
    imei: '123789456123789',
    condition: 'New',
    color: 'Rose Gold',
    storage: '128GB',
    availability: 'Out of Stock',
    image: 'https://billing.mobixpress.in/uploads/brand/vivo.jpg',
    discount: 1000,
  },
  {
    id: 12,
    name: 'Google ',
    price: '49999/-',
    branch: 'MUMBAI',
    age: '6 months',
    imei: '112233445566778',
    condition: 'Used',
    color: 'Stormy Black',
    storage: '128GB',
    availability: 'In Stock',
    image: 'https://billing.mobixpress.in/uploads/brand/ass.jpg',
    discount: 1000,
  },
  {
    id: 13,
    name: 'Sony',
    price: '62999/-',
    branch: 'KOLKATA',
    age: '1 year',
    imei: '223344556677889',
    condition: 'New',
    color: 'Grey',
    storage: '128GB',
    availability: 'In Stock',
    image: 'https://billing.mobixpress.in/uploads/brand/iphone.jpg',
    discount: 1000,
  },
  {
    id: 14,
    name: 'Huawei',
    price: '79999/-',
    branch: 'BARRACKPORE',
    age: '8 months',
    imei: '778899001122334',
    condition: 'Used',
    color: 'Silver',
    storage: '256GB',
    availability: 'In Stock',
    image: 'https://billing.mobixpress.in/uploads/brand/iphone.jpg',
  },
  {
    id: 15,
    name: 'Asus',
    price: '42999/-',
    branch: 'DELHI',
    age: '7 months',
    imei: '334455667788990',
    condition: 'New',
    color: 'Midnight Black',
    storage: '128GB',
    availability: 'Out of Stock',
    image: 'https://billing.mobixpress.in/uploads/brand/iphone.jpg',
  },
  {
    id: 16,
    name: 'Samsung',
    price: '26999/-',
    branch: 'MUMBAI',
    age: '4 months',
    imei: '112233445577889',
    condition: 'New',
    color: 'Awesome Black',
    storage: '128GB',
    availability: 'In Stock',
    image: 'https://billing.mobixpress.in/uploads/brand/iphone.jpg',
  },
  {
    id: 17,
    name: 'Apple',
    price: '42999/-',
    branch: 'BARRACKPORE',
    age: 'New',
    imei: '667788990011223',
    condition: 'New',
    color: 'Midnight',
    storage: '64GB',
    availability: 'In Stock',
    image: 'https://billing.mobixpress.in/uploads/brand/iphone.jpg',
  },
  {
    id: 18,
    name: 'Motorola',
    price: '42999/-',
    branch: 'DELHI',
    age: '1 year',
    imei: '998877665544332',
    condition: 'Used',
    color: 'Blue',
    storage: '128GB',
    availability: 'In Stock',
    image: 'https://billing.mobixpress.in/uploads/brand/vivo.jpg',
  },
  {
    id: 19,
    name: 'Xiaomi',
    price: '27999/-',
    branch: 'KOLKATA',
    age: '5 months',
    imei: '224466881122334',
    condition: 'New',
    color: 'Silver',
    storage: '256GB',
    availability: 'Out of Stock',
    image: 'https://billing.mobixpress.in/uploads/brand/vivo.jpg',
  },
  {
    id: 20,
    name: 'Nokia',
    price: '24999/-',
    branch: 'MUMBAI',
    age: '2 months',
    imei: '556677889900112',
    condition: 'Used',
    color: 'Nordic Blue',
    storage: '128GB',
    availability: 'In Stock',
    image: 'https://billing.mobixpress.in/uploads/brand/vivo.jpg',
  },
];
