export const productItem = [
  {
    name: 'VIVO V21 5G',
    price: '7499/-',
    branch: 'BARRACKPORE',
    age: '6 months',
    imei: '123456789012345',
    condition: 'Used',
    color: 'Black',
    storage: '6/128GB',
    availability: 'In Stock',
    image: 'https://billing.mobixpress.in/uploads/model/SAMSUNG_Galaxy_F04SDSC.jpg',
    discount: 1000,
  },
  {
    name: 'VIVO Y53s',
    price: '23000/-',
    branch: 'KOLKATA',
    age: '1 year',
    imei: '987654321012345',
    condition: 'New',
    color: 'Silver',
    storage: '8/256GB',
    availability: 'Out of Stock',
    image: 'https://billing.mobixpress.in/uploads/model/REDMI_12C_(1).jpg',
    discount: 1100,
  },
  {
    name: 'REALME Narzo 50A',
    price: '10999/-',
    branch: 'BARRACKPORE',
    age: '8 months',
    imei: '192837465091283',
    condition: 'Used',
    color: 'Blue',
    storage: '4/64GB',
    availability: 'In Stock',
    image: 'https://billing.mobixpress.in/uploads/model/SAMSUNG_Galaxy_M34_5G_rty.jpg',
    discount: 1000,
  },
  {
    name: 'Samsung Galaxy S21',
    price: '29999/-',
    branch: 'KOLKATA',
    age: '1 year',
    imei: '456789012345678',
    condition: 'New',
    color: 'White',
    storage: '6/128GB',
    availability: 'In Stock',
    image: 'https://billing.mobixpress.in/uploads/model/APPLE_IPHONE_14_PRO_MAX_(1).jpg',
    discount: 1500,
  },
  {
    name: 'OnePlus 9 Pro',
    price: '35999/-',
    branch: 'BARRACKPORE',
    age: '5 months',
    imei: '654987123456789',
    condition: 'New',
    color: 'Green',
    storage: '6/256GB',
    availability: 'In Stock',
    image: 'https://billing.mobixpress.in/uploads/model/VIVO_V29E_5G_(1).jpg',
    discount: 1600,
  },
  {
    name: 'iPhone 14 Pro Max',
    price: '99999/-',
    branch: 'BARRACKPORE',
    age: 'New',
    imei: '987654321654987',
    condition: 'New',
    color: 'Space Grey',
    storage: '8/128GB',
    availability: 'In Stock',
    image: 'https://billing.mobixpress.in/uploads/model/MOTOROLA_EDGE_40_NEO.jpg',
    discount: 1700,
  },
  {
    name: 'Xiaomi 11T Pro',
    price: '14999/-',
    branch: 'BARRACKPORE',
    age: '3 months',
    imei: '456123789098654',
    condition: 'Used',
    color: 'Black',
    storage: '4/64GB',
    availability: 'In Stock',
    image: 'https://billing.mobixpress.in/uploads/model/SAMSUNG_GALAXY_S22_ULTRA_5G,_BURGUNDY_(1).jpg',
    discount: 1800,
  },
  {
    name: 'Oppo Reno 6 Pro',
    price: '23999/-',
    branch: 'KOLKATA',
    age: '2 months',
    imei: '567123456123789',
    condition: 'Used',
    color: 'Purple',
    storage: '6/128GB',
    availability: 'Out of Stock',
    image: 'https://billing.mobixpress.in/uploads/model/SAMSUNG_GALAXY_S22_ULTRA_5G,_BURGUNDY_(1).jpg',
    discount: 1900,
  },
  {
    name: 'Oppo Reno 6 Pro',
    price: '23999/-',
    branch: 'KOLKATA',
    age: '2 months',
    imei: '567123456123789',
    condition: 'Used',
    color: 'Purple',
    storage: '6/128GB',
    availability: 'Out of Stock',
    image: 'https://billing.mobixpress.in/uploads/model/SAMSUNG_GALAXY_S22_ULTRA_5G,_BURGUNDY_(1).jpg',
    discount: 1900,
  },
 
];
